<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>GflChibiDesktop</RootNamespace>
    <AssemblyName>GflChibiDesktop</AssemblyName>
    <ApplicationIcon>hk416_happy.ico</ApplicationIcon>
    <StartupObject>GflChibiDesktop.App</StartupObject>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <Prefer32Bit>false</Prefer32Bit>
    <Platforms>AnyCPU</Platforms>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>false</SelfContained>
    <SupportedOSPlatformVersion>7.0</SupportedOSPlatformVersion>
    <NoWarn>$(NoWarn);SYSLIB0014;CA1416</NoWarn>
    <AssemblyTitle>少女前线桌面Q宠</AssemblyTitle>
    <Product>GflChibiDesktop</Product>
    <AssemblyProduct>GflChibiDesktop</AssemblyProduct>
    <Company>BrightSu</Company>
    <Copyright>© 2020~2026 BrightSu</Copyright>
    <Description>GflChibiDesktop</Description>
    <AssemblyVersion>1.1.0.1</AssemblyVersion>
    <FileVersion>1.1.0.1</FileVersion>
	<InformationalVersion>20260828</InformationalVersion>
    <PackageProjectUrl>https://projects.brightsu.cn/GflChibiDesktop/V1/</PackageProjectUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HandyControl" Version="3.3.0" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.39" />
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.1.303" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="6.0.0" />
    <PackageReference Include="System.Drawing.Common" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="hk416_happy.ico" />
    <Resource Include="hk416_angry.ico" />
    <Resource Include="background-tile-yellow.png" />
    <Resource Include="background-tile-purple.png" />
  </ItemGroup>

  <ItemGroup>
    <None Include="chibi_list.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <Link>app\chibi_list.json</Link>
    </None>
  </ItemGroup>

</Project>
